### ISSUE TITLE
MBF-41 Design Firestore Users Collection

### ISSUE THREAD

**Issue by karthik-Jay** [bettersg/Mendisphere#41]

**Comment by karthik-Jay** [comment]
registration component lives in this branch: MBF-0054

**Comment by c6z3h** [comment]
Task breakdown:
- [x] Add useState into src\features\registration\components\goals-form.tsx and src\features\registration\components\org-info-form.tsx to keep track of data entered
- [x] Pass a callback function to src\features\registration\profile-page-setup.tsx and useState there to keep track of organization info
- [x] Setup API to Cloud Firestore
- [x] Actually send some data via the registration form
- [x] Validate database is updated correctly
- [ ] Rebase code onto MBF-00054 after it merges to main
- [x] Setup Cloud Firestore security (good design to implement: https://www.youtube.com/watch?v=rIvskxFO6Qg)
![MindBetter1](https://user-images.githubusercontent.com/29767694/218241632-360fa76b-acca-4a01-b040-58bc87f4ba51.png)
![MindBetter2](https://user-images.githubusercontent.com/29767694/218241635-8ba61ffa-59a6-4674-a40a-811928a9cb24.png)

**Comment by c6z3h** [comment]
@karthik-Jay having 2 issues integrating at the moment:

**Comment by karthik-Jay** [comment]
To be merged after completion of registration page.
