### ISSUE TITLE
Develop components in home page

### ISSUE THREAD

**Issue by karthik-Jay** [bettersg/Mendisphere#59]
Goal:

- Create the below components in home page

![Image](https://user-images.githubusercontent.com/32955712/222909486-0549bd03-87ff-4e5b-a337-f8f75ec70cdc.png)

**Comment by karthik-Jay** [comment]
Zhi Hong, would you be able to work on this if you have some capacity this coming week? Dhruv doesn't have capacity for the next couple of weeks @c6z3h

**Comment by audreyaudz** [comment]
I'll do this. Thanks.
