### ISSUE TITLE
Design org profile content data structure

### ISSUE THREAD

**Issue by karthik-Jay** [bettersg/Mendisphere#64]
Data structure is specifically for: 

![Image](https://user-images.githubusercontent.com/32955712/218252243-e792bdc2-f357-4e92-bc0f-78a37e381ac8.png)

**Comment by c6z3h** [comment]
aye, updated in the Entity Relationship Diagram on Miro App~

**Comment by karthik-Jay** [comment]
To be revisted after design team has completed tabs.
