### ISSUE TITLE
Registration page password validator component

### ISSUE THREAD

**Issue by AngKokLeong** [bettersg/Mendisphere#7]
![Image](https://user-images.githubusercontent.com/32955712/221347734-64f8ea1f-ffca-49c6-a31b-542dc979c52b.png)

**Comment by karthik-Jay** [comment]
@audreyaudz are you able to look at this one? Please note the registration page is currently unmerged in master so you will have to continue from branch `MBF-00054`

**Comment by karthik-Jay** [comment]
@audreyaudz please refer to the registration design for styling requirements: https://www.figma.com/file/qdd55HyIgTj4WHHG9dSUBF/Mental-Health-Organisation-Support-Platform?node-id=183%3A2425&t=HGASoTc728CrRIgi-0
