### ISSUE TITLE
Update home page nav bar with new styling

### ISSUE THREAD

**Issue by karthik-Jay** [bettersg/Mendisphere#73]
![Image](https://user-images.githubusercontent.com/32955712/223400276-11bf9b55-850c-4e3a-892b-54ffc19ecdc5.png)

**Comment by karthik-Jay** [comment]
@audreyaudz you can work on this next if you're interested? This should be the last step and we'll be done with the home page 😃

**Comment by audreyaudz** [comment]
i've done this and submitted a pull request.
