### ISSUE TITLE
Organisation profile - tab data Component

### ISSUE THREAD

**Issue by karthik-Jay** [bettersg/Mendisphere#75]
Outcome:

- Create mock data structure for organisation profile summary page
- update component to align with new design in organisation profile page.

**Comment by c6z3h** [comment]
Breakdown of tasks:
- [x] Create a local mock data set in VSCode
- [x] Code up the UI **(Can we descope the vertical tabs? it is hard) // 70% done**
- [x] Add the mock data set to firestore
- [x] Integrate src/services and Firestore rules to retrieve data
