### ISSUE TITLE
Deploy app in GCP test environment

### ISSUE THREAD

**Issue by karthik-Jay** [bettersg/Mendisphere#79]
Outcome:

- create test environment
- deploy latest version of main branch into test environment
- give developers and design team access

**Comment by c6z3h** [comment]
Attempting to break task down further...
- [x] Setup CI GitHub Actions (free for GitHub's runners on Public repositories) to check compile correctly on PR to main; in the future, run unit tests (will we even do that?!)
- [x] Setup Firebase Hosting website for Designer team access
- [x] Ensure that test site will not cost money (set up a GCP billing alert)
- [x] Ask Firebase project owner Joel Kek to downgrade BLAZE PLAN to SPARK PLAN **(he's okay to keep it as is)**
- [x] Setup GitHub Actions to deploy main branch to Firebase Hosting on merge https://github.com/orgs/community/discussions/26724#discussioncomment-3253093
- [x] Create a new IAM account on Firebase for purpose of deployment `${{ secrets.FIREBASE_SERVICE_ACCOUNT_MENDISPHERE }}` https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md
- [x] Validate build on PR works (this PR)
- [ ] Validate deploy on merge PR to main works (this PR)
