### ISSUE TITLE
bug: Non-root React Pages return 404 error

### ISSUE THREAD

**Issue by c6z3h** [bettersg/Mendisphere#90]
**Test Steps:** Access a non-root route (eg. https://mendisphere-test.web.app/organisations )
**Actual Behavior:** Firebase 404 error returns.
**Expected Behavior:** Go to organisation listing page.

**Investigation:**
1. This is because on React's first render, we only get the index.html which points to root route ( https://mendisphere-test.web.app ). JS only loads after that, which provides the Client-side `react-router-dom` to access non-root routes like ( /organisations/ ).
2. This discussion has some possible solutions, with pros and cons discussed https://stackoverflow.com/a/36623117 .
3. Tried to explore if Firebase has a handler for this, read about Dynamic Links here https://firebase.google.com/docs/dynamic-links/custom-domains#priority_order but I don't think that's it.

**Actions Required:**
1. Investigate further if Firebase has a handler for such.
2. If a cheap solution in the stackoverflow post is acceptable, implement it.

**Comment by karthik-Jay** [comment]
![image](https://user-images.githubusercontent.com/32955712/221349812-b635e2a0-1133-47f2-9a48-c9e21596729b.png)

**Comment by c6z3h** [comment]
> ![image](https://user-images.githubusercontent.com/32955712/221349812-b635e2a0-1133-47f2-9a48-c9e21596729b.png)

This new issue is fixed. Now just the 404 error is left
